# Description:
# This script generates an Excel template with the appropriate columns for texture features and rows for each subject
# Subject row can either be generated by looking at the subject folders in the root directory or by manually adding them, following the exact format 
#
# Note: must share the same config files as extract_features.py to ensure consistency. 


import os
import pandas as pd


# location of subject folders, 
# this script only uses the folder names to build rows and does nothing with the contents.
#ROOT_DIR = "./qaqc_test"
#ROOT_DIR = "./qaqc/UHC_Template_OnlyROI"
ROOT_DIR = "./qaqc/dan"


FEATURES_FILE = "config/features_mean.txt"
#FEATURES_FILE = "config/features.txt"
#FEATURES_FILE = "config/features_v2.txt"
#FEATURES_FILE = "config/features_all.txt"


#ROIS_FILE = "config/rois_old.txt"
ROIS_FILE = "config/rois.txt"



# =========================
# SUBJECT ID NORMALISATION
# =========================
#
# Keeps the subject naming consistent between:
# generate_template.py
# extract_features.py
#
# Example:
#
# dsir-1234-brain
# becomes
# dsir-1234
#

def normalise_subject_id(folder):

    subject_id = folder

    # Handles folders such as:
    # subject_scan
    # subject_brain

    if "_" in subject_id:
        subject_id = subject_id.split("_")[0]


    # Handles folders such as:
    # dsir-1234-brain

    subject_id = subject_id.replace(
        "-brain",
        ""
    )

    return subject_id



# load config

with open(ROIS_FILE) as f:
    ROIS = [
        line.strip()
        for line in f
        if line.strip()
    ]


with open(FEATURES_FILE) as f:
    FEATURES = [
        line.strip()
        for line in f
        if line.strip()
    ]



# define columns

columns = ["Subject"]


# append columns based on config.

for roi in ROIS:

    for feat in FEATURES:

        columns.append(
            f"{roi}_{feat}"
        )


# remove duplicates in case pandas adds any.

columns = list(
    dict.fromkeys(columns)
)



# loop through subjects and add them as the rows.
# uses same checking as extract_features.py.

subjects = []


for folder in os.listdir(ROOT_DIR):

    folder_path = os.path.join(
        ROOT_DIR,
        folder
    )


    if os.path.isdir(folder_path):

        subjects.append(
            normalise_subject_id(folder)
        )



subjects = sorted(
    set(subjects)
)



# create an empty DataFrame with the columns and subjects as rows,
# then save it as an Excel file to be filled in later.

df = pd.DataFrame(
    columns=columns
)


df["Subject"] = subjects


df.to_excel(
    "texture_features_template.xlsx",
    index=False
)


print(
    "Template created"
)

print(
    "Subjects:",
    len(subjects)
)